### ISSUE TITLE
privateKeyderive notes

### ISSUE THREAD

**Issue by fanatid** [Ayms/bitcoin-wallets#2]
`bn.cmp(n) >= 0` -- no better way for do this

instead `bn = bn.mod(n);` you can do `bn.isub(n)` because `privateKey` and `IL` BOTH less than `n`, it is means that `privateKey + IL` always less than `2 * n`, because this we can use `sub` here (for speed)

**Comment by Ayms** [comment]
OK, thanks, modified, probably did something wrong before since using isub was not providing the correct result
